"""fix workspace invitation token

Revision ID: dca6068b169e
Revises: 
Create Date: 2026-03-05 12:12:46.747559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca6068b169e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workspace_invitations', 'invited_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_workspace_invitations_email', table_name='workspace_invitations')
    op.drop_column('workspace_invitations', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspace_invitations', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_workspace_invitations_email', 'workspace_invitations', ['email'], unique=False)
    op.alter_column('workspace_invitations', 'invited_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
